expr {=
def Allow {=
	var identity data;
	do {=
		return true;
	}
};
def CheckNewUser {=
	var identity data;
	do {=
		return {=has identity.data 'touristNum'} and {=empty identity.data.touristNum};
	}
};
def EditOwnPohod {=
	var identity data;
	do {=
		return
			{=bool
				identity.data.touristNum
				and(
					identity.data.touristNum == data.chiefNum
					or
					identity.data.touristNum == data.altChiefNum
				)
			}
	}
};
}